// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANdK-aS4UZaSLaADdYtfOImQS_ns6sTcI',
    appId: '1:117706143244:web:4fb00667bd296c2731e029',
    messagingSenderId: '117706143244',
    projectId: 'safezone-4ae36',
    authDomain: 'safezone-4ae36.firebaseapp.com',
    storageBucket: 'safezone-4ae36.firebasestorage.app',
    measurementId: 'G-SVLN0FJMGE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxIX0rX9FDeG8PisFTFMeiXai56dhqjB4',
    appId: '1:117706143244:android:69cd9503eee0918d31e029',
    messagingSenderId: '117706143244',
    projectId: 'safezone-4ae36',
    storageBucket: 'safezone-4ae36.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAag16Cp4zc3Ae7mo9Nvnj3WzFYMwfOmto',
    appId: '1:117706143244:ios:a66762f0ed66769731e029',
    messagingSenderId: '117706143244',
    projectId: 'safezone-4ae36',
    storageBucket: 'safezone-4ae36.firebasestorage.app',
    iosBundleId: 'com.example.safezone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAag16Cp4zc3Ae7mo9Nvnj3WzFYMwfOmto',
    appId: '1:117706143244:ios:a66762f0ed66769731e029',
    messagingSenderId: '117706143244',
    projectId: 'safezone-4ae36',
    storageBucket: 'safezone-4ae36.firebasestorage.app',
    iosBundleId: 'com.example.safezone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANdK-aS4UZaSLaADdYtfOImQS_ns6sTcI',
    appId: '1:117706143244:web:559e5a40b5394c2e31e029',
    messagingSenderId: '117706143244',
    projectId: 'safezone-4ae36',
    authDomain: 'safezone-4ae36.firebaseapp.com',
    storageBucket: 'safezone-4ae36.firebasestorage.app',
    measurementId: 'G-8S2R7GLERS',
  );
}
